### ISSUE TITLE
fails on fedora at node install.js

### ISSUE THREAD

**Issue by diethardsteiner** [jdormit/livre#16]
I get following error when installing:

```
> electron@1.6.6 postinstall /home/dsteiner/git/livre/node_modules/electron
> node install.js

/home/dsteiner/git/livre/node_modules/electron/install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat '/home/dsteiner/git/livre/node_modules/electron/dist/resources'
    at Error (native)
npm ERR! Linux 4.10.12-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

Can you please look into this?

**Comment by diethardsteiner** [comment]
I tried to install another electron app and the behaviour is the same. I tried to Google for the error but couldn't find any solution. I am running this on Fedora 25.

**Comment by diethardsteiner** [comment]
Seems to be related to [this issue](https://github.com/electron/electron/issues/9323)

**Comment by jdormit** [comment]
Did this happen when you ran `npm install` in the Livre directory?

It seems to be an issue with upstream Electron rather than an issue with Livre itself.

**Comment by diethardsteiner** [comment]
Yes, exactly. The issue just got resolved and all is working fine.
